on:
  release:
    types:
      - released
jobs:
  deploy_production:
    name: 🚀 Deploy Production
    environment: production
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: 📜 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0